-- Olta Atlas general-area coordinate batch 01 (10 province-checked records).
-- Coordinates are copied from each source page's spatialCoverage, then reverse-geocoded with OpenStreetMap Nominatim to confirm the province.
-- These are source candidates for general area discovery, not fishing-access points and not verified waterbody centroids.
ALTER TABLE public.fishing_areas ADD COLUMN IF NOT EXISTS latitude double precision;
ALTER TABLE public.fishing_areas ADD COLUMN IF NOT EXISTS longitude double precision;
ALTER TABLE public.fishing_areas ADD COLUMN IF NOT EXISTS coordinate_status text NOT NULL DEFAULT 'not_imported';
ALTER TABLE public.fishing_areas ADD COLUMN IF NOT EXISTS coordinate_note text;

UPDATE public.fishing_areas SET latitude=38.2473928, longitude=36.1705626, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='78e188d0-229d-47d6-813a-93b523bbe95d' AND source_slug='ankara-500km-adana-akpinar-goleti' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=36.813118, longitude=35.6868195, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='8a7d9dc0-b495-4b7f-8076-1e8ece625415' AND source_slug='ankara-500km-adana-ayvalik-goleti' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=37.8369421, longitude=35.7325136, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='d16755fe-1e78-43a8-9015-ffabcf628930' AND source_slug='ankara-500km-adana-bagdere' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=37.2082323, longitude=35.2358087, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='00f5df9f-9fc0-473e-8aba-c98a402d2443' AND source_slug='ankara-500km-adana-buyukkandak-deresi' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=37.2909269, longitude=35.0276023, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='ef6139d2-0c3d-4f21-af8c-2b2be39f53ac' AND source_slug='ankara-500km-adana-cakit-suyu' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=38.1823795, longitude=36.0844499, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='9b7ef7ec-2174-430f-ace5-f9ba837e42a7' AND source_slug='ankara-500km-adana-catalcam-goleti' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=37.3361054, longitude=35.2349688, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='731670ce-b869-4733-a2c4-9750bcfd7b16' AND source_slug='ankara-500km-adana-eglence-cayi' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=37.6489706, longitude=35.6308683, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='b06053ca-b663-484d-a059-969ed1094900' AND source_slug='ankara-500km-adana-gokdere-kopru-baraj-golu' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=37.8832232, longitude=35.9388243, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='a27380c0-40fc-46fd-922d-bcedb225a6bd' AND source_slug='ankara-500km-adana-goksu' AND latitude IS NULL AND longitude IS NULL;
UPDATE public.fishing_areas SET latitude=37.5924828, longitude=35.5709854, coordinates_imported=true, coordinate_status='province_checked_source_candidate', coordinate_note='Olta Atlas spatialCoverage coordinate; reverse-geocoded province match: Adana; source grade D. General area marker only, not a fishing-access point; exact waterbody geometry has not been independently confirmed.', source_checked_at=now() WHERE id='d92c4e11-c1f1-4185-aace-55c5e6335e9c' AND source_slug='ankara-500km-adana-kavsak-bendi-baraj-golu' AND latitude IS NULL AND longitude IS NULL;
