-- Batch 04 was rejected during source-quality review and intentionally applies no coordinates.
-- Reason: the public inventory map contains many rounded/reused administrative-area points;
-- even exact name + province matches do not establish that a point represents the waterbody itself.
-- The three tentative updates from this batch were rolled back in Supabase.
-- Use OpenStreetMap/GeoNames candidates only when both the named feature and province match,
-- and keep independent verification status explicit.
