import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { getFishDetail } from '../../src/lib/data';
import type { FishDetail } from '../../src/types/database';

const months = ['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];

export default function FishDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter();
  const [detail,setDetail]=useState<FishDetail|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!id)return;let active=true;getFishDetail(id).then(r=>{if(!active)return;setDetail(r.data);setError(r.error?'Bazı bilgiler yüklenemedi.':null);setLoading(false)});return()=>{active=false}},[id]);
  if(loading)return <SafeAreaView style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Balık bilgileri yükleniyor...</Text></SafeAreaView>;
  if(!detail)return <SafeAreaView style={styles.center}><Text>Balık kaydı bulunamadı.</Text><Pressable onPress={()=>router.back()}><Text style={styles.link}>Geri dön</Text></Pressable></SafeAreaView>;
  const {fish,methods,baits,rules,waterBodies,activity}=detail;
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}>
    <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Geri</Text></Pressable>
    <Text style={styles.title}>{fish.common_name_tr}</Text>{fish.scientific_name?<Text style={styles.scientific}>{fish.scientific_name}</Text>:null}{fish.description?<Text style={styles.description}>{fish.description}</Text>:null}
    {error?<View style={styles.warning}><Text style={styles.warningText}>{error} Eksik bilgiler kesin bilgi olarak değerlendirilmemelidir.</Text></View>:null}
    <GuideSection title="Yaşam alanı"><Text style={styles.body}>{fish.habitat||'Habitat bilgisi henüz eklenmemiş.'}</Text></GuideSection>
    <GuideSection title="Mevsimsel aktivite"><Text style={styles.muted}>Bu takvim genel tür aktivitesidir; yasal av döneminin yerine geçmez.</Text>{activity.length?<View style={styles.calendar}>{months.map((m,i)=>{const a=activity.find(x=>x.month===i+1);return <View key={m} style={styles.month}><Text style={styles.monthText}>{m}</Text><View style={[styles.dot,a?.activity_level==='high'&&styles.high,a?.activity_level==='medium'&&styles.medium,a?.activity_level==='low'&&styles.low]}/></View>})}</View>:<Text style={[styles.muted,{marginTop:10}]}>Henüz kaynaklandırılmış aylık aktivite verisi yok.</Text>}{activity.map(a=><View key={a.id} style={styles.row}><Text style={styles.name}>{months[a.month-1]} — {a.activity_level==='high'?'yüksek':a.activity_level==='medium'?'orta':'düşük'} aktivite</Text>{a.depth_note?<Text style={styles.body}>Derinlik: {a.depth_note}</Text>:null}{a.method_note?<Text style={styles.body}>Yöntem: {a.method_note}</Text>:null}{a.bait_note?<Text style={styles.body}>Yem: {a.bait_note}</Text>:null}{a.source_url?<Text style={styles.source}>{a.source_url}</Text>:null}</View>)}</GuideSection>
    <GuideSection title="Av yöntemleri">{methods.length?methods.map(x=><View key={x.id} style={styles.row}><Text style={styles.name}>{x.name}</Text>{x.description?<Text style={styles.body}>{x.description}</Text>:null}{x.suitable_for?<Text style={styles.meta}>{x.suitable_for}</Text>:null}</View>):<Text style={styles.muted}>Doğrulanmış yöntem kaydı henüz yok.</Text>}</GuideSection>
    <GuideSection title="Yemler">{baits.length?baits.map(x=><View key={x.id} style={styles.row}><Text style={styles.name}>{x.name}</Text>{x.description?<Text style={styles.body}>{x.description}</Text>:null}{x.notes?<Text style={styles.meta}>{x.notes}</Text>:null}</View>):<Text style={styles.muted}>Doğrulanmış yem kaydı henüz yok.</Text>}</GuideSection>
    <GuideSection title="Güncel kurallar">{rules.length?rules.map(x=><View key={x.id} style={styles.row}><Text style={styles.name}>{x.title}</Text><Text style={styles.body}>{x.summary}</Text>{x.effective_from||x.effective_to?<Text style={styles.meta}>Geçerlilik: {x.effective_from??'—'} → {x.effective_to??'—'}</Text>:null}{x.source_url?<Text style={styles.source}>{x.source_url}</Text>:null}</View>):<Text style={styles.muted}>Bu tür için doğrulanmış kural kaydı bulunmuyor. Güncel resmi mevzuat ayrıca kontrol edilmelidir.</Text>}</GuideSection>
    <GuideSection title="Bu balığın bulunduğu sular">{waterBodies.length?waterBodies.map(w=><Pressable key={w.id} onPress={()=>router.push(`/water-body/${w.id}`)} style={styles.waterRow}><View style={styles.waterText}><Text style={styles.name}>{w.name}</Text><Text style={styles.muted}>{[w.province,w.district].filter(Boolean).join(' • ')}</Text>{w.water_type?<Text style={styles.meta}>{w.water_type}</Text>:null}</View><Text style={styles.arrow}>›</Text></Pressable>):<Text style={styles.muted}>Henüz ilişkilendirilmiş su kaynağı bulunmuyor.</Text>}</GuideSection>
    <Pressable style={styles.mapButton} onPress={()=>router.push('/map')}><Text style={styles.mapButtonText}>Haritada su kaynaklarını aç</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
function GuideSection({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#f6f8f7'},content:{padding:18,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},back:{fontWeight:'800',color:'#087f5b',marginBottom:14},title:{fontSize:30,fontWeight:'800',color:'#123b32'},scientific:{fontStyle:'italic',color:'#71817b',marginTop:3},description:{color:'#4f625b',lineHeight:21,marginTop:12},section:{backgroundColor:'#fff',borderRadius:16,padding:16,marginTop:14,borderWidth:1,borderColor:'#dbe5e1'},sectionTitle:{fontSize:19,fontWeight:'800',color:'#17352e',marginBottom:10},row:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#edf2ef'},waterRow:{paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#edf2ef',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},waterText:{flex:1},name:{fontSize:16,fontWeight:'800',color:'#17352e'},body:{color:'#4f625b',lineHeight:19,marginTop:4},meta:{color:'#087f5b',fontWeight:'600',marginTop:6},muted:{color:'#71817b'},link:{color:'#087f5b',fontWeight:'800'},source:{fontSize:11,color:'#71817b',marginTop:6},warning:{marginTop:14,backgroundColor:'#fff6df',borderRadius:12,padding:12,borderWidth:1,borderColor:'#ead7a0'},warningText:{color:'#765c20',lineHeight:19},arrow:{fontSize:28,color:'#087f5b',paddingLeft:10},mapButton:{marginTop:14,backgroundColor:'#087f5b',borderRadius:14,padding:14,alignItems:'center'},mapButtonText:{color:'#fff',fontWeight:'800'},calendar:{flexDirection:'row',justifyContent:'space-between',marginTop:14},month:{alignItems:'center'},monthText:{fontSize:10,color:'#687771'},dot:{width:16,height:16,borderRadius:8,backgroundColor:'#dce5e1',marginTop:5},high:{backgroundColor:'#087f5b'},medium:{backgroundColor:'#74b8a2'},low:{backgroundColor:'#c8d8d2'}});