import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Linking, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { getFishingAreas, getWaterBodies } from '../src/lib/data';
import type { FishingArea, WaterBody } from '../src/types/database';

type Filter = 'all' | 'mera' | 'reservoir' | 'natural_lake' | 'pond' | 'river';
type Row = { key:string; name:string; province:string|null; type:string|null; lat:number|null; lon:number|null; water:WaterBody|null; atlas:FishingArea|null; note:string|null; confidence:string|null; checked:string|null };
const filters:{key:Filter;label:string}[]=[{key:'all',label:'Tümü'},{key:'mera',label:'Meralar'},{key:'reservoir',label:'Barajlar'},{key:'natural_lake',label:'Göller'},{key:'pond',label:'Göletler'},{key:'river',label:'Akarsular'}];
const norm=(v:string|null|undefined)=>(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('tr-TR').replace(/[^a-z0-9]/g,'');
const core=(v:string)=>norm(v.replace(/^[^-]+-/,''));
function kind(v:string|null|undefined,name=''):Filter{const s=norm((v??'')+' '+name);if(s.includes('baraj')||s.includes('reservoir')||s.includes('dam'))return'reservoir';if(s.includes('golet')||s.includes('pond'))return'pond';if(s.includes('akarsu')||s.includes('dere')||s.includes('river')||s.includes('stream')||s.includes('watercourse'))return'river';if(s.includes('gol')||s.includes('lake'))return'natural_lake';return'all';}
function label(v:string|null|undefined,name=''){const k=kind(v,name);return k==='reservoir'?'Baraj gölü':k==='natural_lake'?'Göl':k==='pond'?'Gölet':k==='river'?'Akarsu / dere':v||'Su kaynağı';}
function confidence(v:string|null|undefined){if(!v)return'Güven düzeyi belirtilmemiş';const s=v.toUpperCase();return s==='A'?'Yüksek güven':s==='B'?'İyi güven':s==='C'?'Orta güven':s==='D'||s==='F'?'Sınırlı / doğrulanmamış':v;}
async function openUrl(url:string|null|undefined){if(!url)return;try{await Linking.openURL(url);}catch{Alert.alert('Bağlantı açılamadı','Bağlantı cihazında açılamadı.');}}

export default function MeralarScreen(){
 const [waters,setWaters]=useState<WaterBody[]>([]);const [areas,setAreas]=useState<FishingArea[]>([]);const [search,setSearch]=useState('');const [filter,setFilter]=useState<Filter>('all');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [w,a]=await Promise.all([getWaterBodies(),getFishingAreas()]);setWaters(w.data);setAreas(a.data);if(w.error&&a.error)setError('Hiçbir kaynak yüklenemedi. Bağlantını kontrol edip tekrar dene.');else if(w.error||a.error)setError('Kaynaklardan biri yüklenemedi; diğer kaynaktaki kayıtlar gösteriliyor.');}catch{setError('Katalog yüklenemedi. Lütfen tekrar dene.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const catalog=useMemo<Row[]>(()=>{const rows:Row[]=[];const used=new Set<string>();for(const w of waters){const match=areas.find(a=>!used.has(a.id)&&core(a.name)===core(w.name)&&(!a.province_name||!w.province||norm(a.province_name)===norm(w.province)));if(match)used.add(match.id);rows.push({key:'water:'+w.id,name:w.name,province:w.province??match?.province_name??null,type:w.water_type??match?.water_type??null,lat:w.latitude??match?.latitude??null,lon:w.longitude??match?.longitude??null,water:w,atlas:match??null,note:match?.general_note??w.description??null,confidence:match?.location_confidence_grade??w.coordinate_confidence_grade??w.verification_level??null,checked:match?.source_checked_at??w.last_verified_at??null});}for(const a of areas){if(used.has(a.id))continue;rows.push({key:'atlas:'+a.id,name:a.name,province:a.province_name??null,type:a.water_type??null,lat:a.latitude==null?null:Number(a.latitude),lon:a.longitude==null?null:Number(a.longitude),water:null,atlas:a,note:a.general_note??null,confidence:a.location_confidence_grade??a.source_grade??null,checked:a.source_checked_at??null});}return rows;},[waters,areas]);
 const q=search.trim().toLocaleLowerCase('tr-TR');const filtered=useMemo(()=>catalog.filter(r=>(!q||[r.name,r.province,r.type,r.note,r.water?'Balık Rehberi':'',r.atlas?'Olta Atlası':''].filter(Boolean).some(v=>String(v).toLocaleLowerCase('tr-TR').includes(q)))&&(filter==='all'||(filter==='mera'?!r.water:kind(r.type,r.name)===filter))),[catalog,q,filter]);
 const openMap=(r:Row)=>{if(r.lat==null||r.lon==null){Alert.alert('Konum yok','Bu kayıt için genel koordinat bulunmuyor.');return;}const lat=Number(r.lat),lon=Number(r.lon);Alert.alert('Genel konumu aç','Bu işaret kıyı erişimi veya avlanma izni değildir.',[{text:'Google Maps',onPress:()=>void openUrl('https://www.google.com/maps/search/?api=1&query='+lat+','+lon)},{text:'Yandex Maps',onPress:()=>void openUrl('https://yandex.com/maps/?ll='+lon+','+lat+'&z=12&pt='+lon+','+lat)},{text:'Apple Haritalar',onPress:()=>void openUrl('https://maps.apple.com/?ll='+lat+','+lon+'&q='+encodeURIComponent(r.name))},{text:'Vazgeç',style:'cancel'}]);};
 const renderRow=({item:r}:{item:Row})=><View style={styles.card}><View style={[styles.pin,!r.water&&styles.atlasPin]}><Text style={[styles.pinText,!r.water&&styles.atlasPinText]}>{kind(r.type,r.name)==='river'?'A':kind(r.type,r.name)==='reservoir'?'B':'G'}</Text></View><View style={styles.copy}><Pressable onPress={()=>r.water?router.push({pathname:'/water-body/[id]',params:{id:r.water.id}}):void openUrl(r.atlas?.source_url)}><Text style={styles.name}>{r.name}</Text><Text style={styles.meta}>{[r.province,label(r.type,r.name)].filter(Boolean).join(' · ')}</Text></Pressable><View style={styles.badges}>{(r.water&&r.atlas?['Balık Rehberi','Olta Atlası']:r.water?['Balık Rehberi']:['Olta Atlası']).map(s=><View key={s} style={[styles.badge,s==='Olta Atlası'&&styles.atlasBadge]}><Text style={[styles.badgeText,s==='Olta Atlası'&&styles.atlasBadgeText]}>{s}</Text></View>)}</View>{r.note?<Text style={styles.note} numberOfLines={3}>{r.note}</Text>:null}<Text style={styles.confidence}>{confidence(r.confidence)}{r.checked?' · Kontrol: '+new Date(r.checked).toLocaleDateString('tr-TR'):''}</Text><View style={styles.actions}><Pressable onPress={()=>openMap(r)}><Text style={styles.link}>Genel konum ↗</Text></Pressable>{r.atlas?.source_url?<Pressable onPress={()=>void openUrl(r.atlas?.source_url)}><Text style={styles.link}>Olta Atlası kaydı ↗</Text></Pressable>:null}{r.water?.source_url?<Pressable onPress={()=>void openUrl(r.water?.source_url)}><Text style={styles.link}>Kendi kaynağımız ↗</Text></Pressable>:null}</View></View></View>;
 return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.eyebrow}>BİRLEŞİK KAYNAK KATALOĞU</Text><Text style={styles.title}>Meralar & Su Kaynakları</Text><Text style={styles.subtitle}>Meraları ve su kaynaklarını tek katalogda keşfet. Harita işaretleri genel konumu gösterir; birebir av noktası, kıyı erişimi veya izin garantisi değildir.</Text></View><TextInput value={search} onChangeText={setSearch} placeholder="Mera, göl, baraj, akarsu veya il ara..." placeholderTextColor="#7b8794" style={styles.input}/><View style={styles.filters}>{filters.map(x=><Pressable key={x.key} onPress={()=>setFilter(x.key)} style={[styles.filter,filter===x.key&&styles.filterActive]}><Text style={[styles.filterText,filter===x.key&&styles.filterTextActive]}>{x.label}</Text></Pressable>)}</View><View style={styles.summary}><Text style={styles.count}>{filtered.length} kayıt · {catalog.filter(r=>r.water&&r.atlas).length} iki kaynakla eşleşen</Text><Pressable onPress={()=>router.push('/map')}><Text style={styles.link}>Haritayı aç ↗</Text></Pressable></View>{loading?<ActivityIndicator size="large" color="#087f5b" style={{marginTop:24}}/>:error&&catalog.length===0?<View style={styles.state}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>void load()} style={styles.retry}><Text style={styles.retryText}>Tekrar dene</Text></Pressable></View>:<>{error?<Text style={styles.partial}>{error}</Text>:null}<FlatList data={filtered} keyExtractor={r=>r.key} renderItem={renderRow} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>Bu aramayla eşleşen kayıt yok.</Text>}/></>}<View style={styles.bottom}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>‹ Geri</Text></Pressable><Text style={styles.footer}>Genel konum · erişim izni değildir</Text></View></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#f6f8f7',paddingHorizontal:16},header:{paddingTop:12,paddingBottom:12},eyebrow:{color:'#087f5b',fontSize:10,fontWeight:'900',letterSpacing:1.5,marginBottom:6},title:{fontSize:25,fontWeight:'900',color:'#123b32'},subtitle:{fontSize:12,color:'#61706b',lineHeight:18,marginTop:7},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dce5e1',borderRadius:12,paddingHorizontal:14,paddingVertical:12,fontSize:14,color:'#17352e'},filters:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:10},filter:{borderRadius:20,paddingHorizontal:12,paddingVertical:8,backgroundColor:'#e7eeeb'},filterActive:{backgroundColor:'#087f5b'},filterText:{fontSize:11,fontWeight:'800',color:'#47645a'},filterTextActive:{color:'#fff'},summary:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8,marginTop:13,marginBottom:8},count:{color:'#60736b',fontSize:11,fontWeight:'800',flex:1},list:{paddingBottom:20},card:{backgroundColor:'#fff',borderRadius:14,padding:13,marginBottom:9,flexDirection:'row',alignItems:'flex-start',borderWidth:1,borderColor:'#e4ebe7'},pin:{width:36,height:36,borderRadius:12,backgroundColor:'#e2eee9',alignItems:'center',justifyContent:'center',marginRight:11},pinText:{color:'#087f5b',fontWeight:'900'},atlasPin:{backgroundColor:'#e4edf9'},atlasPinText:{color:'#315d91'},copy:{flex:1},name:{fontSize:15,fontWeight:'900',color:'#17352e'},meta:{fontSize:11,color:'#70817b',marginTop:4},badges:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:8},badge:{backgroundColor:'#e2f1e9',borderRadius:8,paddingHorizontal:7,paddingVertical:4},badgeText:{color:'#155d46',fontSize:9,fontWeight:'900'},atlasBadge:{backgroundColor:'#e4edf9'},atlasBadgeText:{color:'#315d91'},note:{color:'#5f716a',fontSize:11,lineHeight:16,marginTop:7},confidence:{color:'#77867f',fontSize:10,lineHeight:15,marginTop:7},actions:{flexDirection:'row',flexWrap:'wrap',gap:13,marginTop:8},link:{color:'#087f5b',fontWeight:'900',fontSize:11},state:{alignItems:'center',padding:30},error:{textAlign:'center',color:'#8a4a42',lineHeight:20},partial:{color:'#805e23',fontSize:11,paddingVertical:5},retry:{marginTop:12,backgroundColor:'#087f5b',paddingHorizontal:18,paddingVertical:10,borderRadius:10},retryText:{color:'#fff',fontWeight:'800'},empty:{textAlign:'center',color:'#687771',padding:30},bottom:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:18,paddingVertical:10,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#dbe5e1'},back:{backgroundColor:'#e2eee9',borderRadius:11,paddingHorizontal:15,paddingVertical:9},backText:{color:'#125744',fontWeight:'900',fontSize:14},footer:{color:'#84928b',fontSize:10}});
