import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { getWaterBodyDetail } from '../../src/lib/data';
import type { WaterBodyDetail } from '../../src/types/database';
import { supabase } from '../../src/config/supabase';

export default function WaterBodyDetailScreen(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const[detail,setDetail]=useState<WaterBodyDetail|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[feedbackSummary,setFeedbackSummary]=useState<any>(null);const[feedbackBusy,setFeedbackBusy]=useState(false);const[feedbackNote,setFeedbackNote]=useState('');
 useEffect(()=>{if(!id){setLoading(false);setError('Su kaynağı kimliği bulunamadı.');return}getWaterBodyDetail(id).then(r=>{setDetail(r.data);setError(r.error?.message??null);setLoading(false)})},[id]);
 useEffect(()=>{let active=true;const loadSummary=async()=>{if(!id||!supabase)return;const {data,error}=await supabase.from('water_body_feedback_summary').select('correct_votes,incorrect_votes,unclear_votes,net_votes,community_confidence_grade').eq('water_body_id',id).maybeSingle();if(active&&!error)setFeedbackSummary(data)};void loadSummary();return()=>{active=false}},[id]);
 const submitFeedback=async(vote:'correct'|'incorrect'|'unclear')=>{if(!supabase){Alert.alert('Bağlantı yok','Geri bildirim şu anda gönderilemiyor.');return}setFeedbackBusy(true);try{let user=(await supabase.auth.getUser()).data.user;if(!user){const {data:anonData,error:authError}=await supabase.auth.signInAnonymously();if(authError)throw new Error('Anonim geri bildirim için Supabase Auth ayarlarında Anonymous Sign-Ins etkin olmalı.');user=anonData.user;}if(!user)throw new Error('Oturum oluşturulamadı.');const {error}=await supabase.from('water_body_location_feedback').upsert({water_body_id:id,user_id:user.id,vote,note:feedbackNote.trim()||null},{onConflict:'water_body_id,user_id'});if(error)throw error;const {data:summary, error:summaryError}=await supabase.from('water_body_feedback_summary').select('correct_votes,incorrect_votes,unclear_votes,community_confidence_grade').eq('water_body_id',id).maybeSingle();if(summaryError)throw summaryError;setFeedbackSummary(summary);setFeedbackNote('');Alert.alert('Geri bildirimin alındı','Bu su kaynağını değerlendirdiğin için teşekkürler. Güven seviyesi farklı hesapların geri bildirimleriyle kademeli güncellenir.')}catch(e:any){Alert.alert('Gönderilemedi',e?.message??'Geri bildirim kaydedilemedi.')}finally{setFeedbackBusy(false)}};
 if(loading)return <SafeAreaView style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Su kaynağı bilgileri yükleniyor...</Text></SafeAreaView>;
 if(!detail)return <SafeAreaView style={styles.center}><Text>{error??'Su kaynağı bulunamadı.'}</Text><Pressable onPress={()=>router.back()}><Text style={styles.link}>Geri dön</Text></Pressable></SafeAreaView>;
 const w=detail.waterBody;
 const openNavigation = async (provider: 'chooser' | 'google' | 'yandex' | 'apple') => {
   if (w.latitude == null || w.longitude == null) {
     Alert.alert('Koordinat bulunamadı', 'Bu su kaynağı için doğrulanmış koordinat olmadığı için yol tarifi açılamıyor.');
     return;
   }
   const lat = Number(w.latitude), lon = Number(w.longitude);
   const label = encodeURIComponent(w.name);
   const google = `https://www.google.com/maps/dir/?api=1&destination=${lat},${lon}`;
   const yandex = `https://yandex.com/maps/?rtext=~${lat},${lon}&rtt=auto`;
   const apple = `https://maps.apple.com/?daddr=${lat},${lon}&q=${label}`;
   const geo = Platform.OS === 'android' ? `geo:${lat},${lon}?q=${lat},${lon}(${label})` : apple;
   const url = provider === 'google' ? google : provider === 'yandex' ? yandex : provider === 'apple' ? apple : geo;
   try { await Linking.openURL(url); }
   catch {
     const fallback = provider === 'yandex' ? yandex : provider === 'apple' ? apple : google;
     try { await Linking.openURL(fallback); }
     catch { Alert.alert('Harita açılamadı', 'Cihazınızda uyumlu bir harita uygulaması veya tarayıcı bulunamadı.'); }
   }
 };
 const showNavigationOptions = () => Alert.alert(
   'Yol tarifi al',
   'Hangi harita uygulamasında açmak istersiniz?',
   [
     { text: 'Google Maps', onPress: () => { void openNavigation('google'); } },
     { text: 'Yandex Maps', onPress: () => { void openNavigation('yandex'); } },
     ...(Platform.OS === 'ios' ? [{ text: 'Apple Haritalar', onPress: () => { void openNavigation('apple'); } }] : []),
     { text: 'Cihazın harita uygulaması', onPress: () => { void openNavigation('chooser'); } },
     { text: 'İptal', style: 'cancel' as const },
   ],
 );
 return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}>
  <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Geri</Text></Pressable><Text style={styles.title}>{w.name}</Text><Text style={styles.location}>{[w.province,w.district].filter(Boolean).join(' • ')||'Konum bilgisi yok'}</Text><View style={styles.badge}><Text style={styles.badgeText}>{w.water_type||'Su kaynağı'}</Text></View>
  <View style={styles.card}><Text style={styles.section}>Kaynak ve doğrulama</Text><View style={styles.grid}><Info label="Kaynak doğrulaması" value={w.verification_level||'Belirtilmemiş'}/><Info label="Koordinat güveni" value={w.coordinate_confidence_grade||'F'}/><Info label="Kayıt durumu" value={w.verification_status||'Belirtilmemiş'}/><Info label="Erişim" value={w.access_level||'Ayrıca kontrol edilmeli'}/><Info label="Son kontrol" value={w.last_verified_at?new Date(w.last_verified_at).toLocaleDateString('tr-TR'):'Belirtilmemiş'}/></View>{w.source_name?<Text style={styles.muted}>Kaynak: {w.source_name}</Text>:null}{w.source_url?<Text style={styles.source}>{w.source_url}</Text>:null}{w.source_reference&&w.source_reference!==w.source_url?<Text style={styles.muted}>Kaynak notu: {w.source_reference}</Text>:null}{w.description?<Text style={styles.body}>{w.description}</Text>:null}{!w.source_url&&!w.source_reference?<Text style={styles.warning}>Doğrudan kaynak bağlantısı bulunmuyor; bu kayıt ayrıca doğrulanmalı.</Text>:null}</View>
  <View style={styles.card}><Text style={styles.section}>Konum güvenilirliği</Text><View style={[styles.confidencePill, confidenceStyle(w.coordinate_confidence_grade)]}><Text style={styles.confidenceText}>{confidenceLabel(w.coordinate_confidence_grade, w.latitude != null && w.longitude != null)}</Text></View><Text style={styles.muted}>{w.coordinate_confidence_note??'Konumun güven seviyesi, kaynak kalitesi ve koordinat eşleşmesine göre belirlenir.'}</Text><Text style={styles.feedbackTitle}>{w.water_type==='natural_lake'?'Bu gölü onayla':w.water_type==='reservoir'?'Bu barajı onayla':w.water_type==='pond'?'Bu göleti onayla':'Bu su kaynağını onayla'}</Text><TextInput value={feedbackNote} onChangeText={setFeedbackNote} placeholder="İstersen kısa bir not ekle (en fazla 500 karakter)" placeholderTextColor="#87958f" maxLength={500} multiline style={styles.feedbackInput}/><Text style={styles.muted}>Her hesap bir su kaynağı için tek oy kullanabilir. 5 net olumlu oy E, 10 D, 15 C, 20 B ve 25 A topluluk seviyesine ulaştırır. Bu puan kaynak doğrulamasından ayrıdır.</Text><View style={styles.feedbackRow}><Pressable disabled={feedbackBusy} style={styles.feedbackButton} onPress={()=>void submitFeedback('correct')}><Text style={styles.feedbackButtonText}>{w.water_type==='natural_lake'?'✓ Gölü onayla':w.water_type==='reservoir'?'✓ Barajı onayla':w.water_type==='pond'?'✓ Göleti onayla':'✓ Konumu onayla'}</Text></Pressable><Pressable disabled={feedbackBusy} style={styles.feedbackButtonBad} onPress={()=>void submitFeedback('incorrect')}><Text style={styles.feedbackButtonText}>✕ Yanlış</Text></Pressable><Pressable disabled={feedbackBusy} style={styles.feedbackButtonNeutral} onPress={()=>void submitFeedback('unclear')}><Text style={styles.feedbackButtonNeutralText}>? Emin değilim</Text></Pressable></View>{feedbackSummary?<Text style={styles.feedbackSummary}>{communityProgress(feedbackSummary)}</Text>:<Text style={styles.feedbackSummary}>Topluluk güveni: F · E seviyesine ulaşmak için 5 net olumlu onay gerekiyor.</Text>}</View>
  <View style={styles.card}><Text style={styles.section}>Avlanma mevzuatı</Text><Text style={styles.status}>⚠️ Bu su kaynağı kaydı tek başına avlanma izni göstermez.</Text><Text style={styles.muted}>Güncel il, su, tür ve tarih kısıtları resmî mevzuatla kontrol edilmelidir. Erişim, özel mülkiyet ve saha güvenliği bilgileri ayrıca doğrulanmalıdır.</Text></View>
  <View style={styles.card}><Text style={styles.section}>Bu suda bulunan balıklar</Text>{detail.fish.length===0?<Text style={styles.muted}>Henüz ilişkilendirilmiş tür kaydı bulunmuyor.</Text>:detail.fish.map(f=><Pressable key={f.id} onPress={()=>router.push(`/fish/${f.id}`)} style={styles.fishRow}><Text style={styles.fishName}>{f.common_name_tr}</Text>{f.scientific_name?<Text style={styles.scientific}>{f.scientific_name}</Text>:null}<Text style={styles.open}>Tür ayrıntısını aç ›</Text></Pressable>)}</View>
  <View style={styles.card}><Text style={styles.section}>Koordinat bilgisi</Text>{w.latitude!=null&&w.longitude!=null?<><Text style={styles.muted}>{Number(w.latitude).toFixed(5)}, {Number(w.longitude).toFixed(5)}</Text><Text style={styles.warning}>Bu koordinat su kaynağını gösterir; kıyı girişi, halka açık erişim veya güvenli varış noktası olduğu ayrıca doğrulanmalıdır.</Text><Pressable style={styles.mapButton} onPress={showNavigationOptions}><Text style={styles.mapButtonText}>Yol tarifi al · Harita uygulamasında aç</Text></Pressable></>:<><Text style={styles.muted}>Bu kayıtta koordinat yok; harita uygulamasında güvenilir yol tarifi oluşturulamıyor.</Text><Pressable style={[styles.mapButton,{opacity:0.5}]} onPress={()=>Alert.alert('Koordinat eksik','Konum doğrulanana kadar yol tarifi bağlantısı oluşturulamaz.')}><Text style={styles.mapButtonText}>Yol tarifi kullanılamıyor</Text></Pressable></>}</View>
 </ScrollView></SafeAreaView>;
}
function communityProgress(summary:any){
 const grade=summary?.community_confidence_grade??'F';
 const steps:Record<string,{next:string;threshold:number}|null>={F:{next:'E',threshold:5},E:{next:'D',threshold:10},D:{next:'C',threshold:15},C:{next:'B',threshold:20},B:{next:'A',threshold:25},A:null};
 const step=steps[grade]??steps.F;
 if(!step)return `Topluluk güveni A · ${summary.correct_votes??0} olumlu · ${summary.incorrect_votes??0} olumsuz. En yüksek topluluk seviyesi.`;
 const net=Number(summary.net_votes??(Number(summary.correct_votes??0)-Number(summary.incorrect_votes??0)));
 const positive=Number(summary.correct_votes??0);
 const remaining=Math.max(0,step.threshold-net,step.threshold-positive);
 return `Topluluk güveni ${grade} · ${summary.correct_votes??0} olumlu · ${summary.incorrect_votes??0} olumsuz. ${step.next} seviyesine geçmek için ${remaining} net olumlu onay daha gerekiyor.`;
}
function Info({label,value}:{label:string;value:string}){return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}
function confidenceLabel(grade:string|null|undefined,hasCoords:boolean){if(!hasCoords||!grade||grade==='F')return 'F · Kontrol ediniz — koordinat eksik';if(grade==='A')return 'A · Güvenilir konum';if(grade==='B')return 'B · Güvenilir genel konum';if(grade==='C')return 'C · Kontrol önerilir';if(grade==='D')return 'D · Düşük güven, kontrol edin';return 'E · Çok düşük güven, kontrol ediniz';}
function confidenceStyle(grade:string|null|undefined){return grade==='A'?{backgroundColor:'#d8f3e4'}:grade==='B'?{backgroundColor:'#e0f0e8'}:grade==='C'?{backgroundColor:'#fff0cc'}:{backgroundColor:'#f9e2dc'};}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#f6f8f7'},content:{padding:18,paddingBottom:40},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},back:{fontWeight:'800',color:'#087f5b',marginBottom:14},title:{fontSize:28,fontWeight:'800',color:'#123b32'},location:{marginTop:5,color:'#71817b'},badge:{alignSelf:'flex-start',backgroundColor:'#dcece7',paddingHorizontal:12,paddingVertical:7,borderRadius:16,marginTop:12},badgeText:{fontWeight:'700',color:'#125744'},card:{backgroundColor:'#fff',borderRadius:16,padding:16,marginTop:14,borderWidth:1,borderColor:'#dbe5e1'},section:{fontSize:18,fontWeight:'800',color:'#17352e',marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},info:{width:'47%',backgroundColor:'#f6f8f7',borderRadius:10,padding:10},infoLabel:{fontSize:11,color:'#71817b'},infoValue:{fontWeight:'800',color:'#17352e',marginTop:4},status:{fontWeight:'700',color:'#765c20',marginBottom:7},fishRow:{paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#edf2ef'},fishName:{fontSize:16,fontWeight:'800',color:'#17352e'},scientific:{fontStyle:'italic',color:'#71817b',marginTop:2},muted:{color:'#71817b',lineHeight:19},body:{color:'#4f625b',lineHeight:19,marginTop:8},warning:{color:'#765c20',lineHeight:19,marginTop:8},open:{color:'#087f5b',fontWeight:'800',marginTop:7},mapButton:{marginTop:12,backgroundColor:'#dcece7',paddingVertical:11,borderRadius:10,alignItems:'center'},mapButtonText:{fontWeight:'800',color:'#125744'},source:{fontSize:11,color:'#71817b',marginTop:8},confidencePill:{alignSelf:'flex-start',paddingHorizontal:12,paddingVertical:8,borderRadius:18,marginBottom:8},confidenceText:{fontWeight:'800',color:'#17352e'},feedbackTitle:{fontWeight:'800',fontSize:15,color:'#17352e',marginTop:14,marginBottom:6},feedbackInput:{backgroundColor:'#f6f8f7',borderWidth:1,borderColor:'#dbe5e1',borderRadius:10,padding:10,minHeight:42,marginTop:5,color:'#17352e'},feedbackRow:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:10},feedbackButton:{backgroundColor:'#dcefe7',paddingHorizontal:12,paddingVertical:10,borderRadius:10},feedbackButtonBad:{backgroundColor:'#f8e2de',paddingHorizontal:12,paddingVertical:10,borderRadius:10},feedbackButtonNeutral:{backgroundColor:'#edf0f2',paddingHorizontal:12,paddingVertical:10,borderRadius:10},feedbackButtonText:{fontWeight:'800',color:'#17352e'},feedbackButtonNeutralText:{fontWeight:'800',color:'#4c5c58'},feedbackSummary:{fontSize:12,color:'#71817b',marginTop:10},link:{color:'#087f5b',fontWeight:'800',marginTop:10}});